grafana:
    image: grafana/grafana:6.5.3
    container_name: grafana
    user: "472"
    volumes:
      - grafana_data:/var/lib/grafana:rw
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=true
    restart: always
    expose:
      - 3000
