version: '2'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
    - /home/mgeweb/monitoring/prometheus:/etc/prometheus/
    ports:
    - 9090:9090
    extra_hosts:
            - "node_rancher_01:172.31.28.131"
            - "node_rancher_02:172.31.23.179"
            - "node_rancher_03:172.31.11.239"
            - "node_rancher_04:172.31.10.44"
            - "node_rancher_05:172.31.0.141"
            - "node_rancher_06:172.31.4.93"
            - "node_rancher_07:172.31.0.68"
            - "node_rancher_08:172.31.1.6"
            - "node_rancher_09:172.31.11.17"
            - "node_rancher_10:172.31.1.133"
            - "node_rancher_11:172.31.11.132"
            - "node_rancher_12:172.31.10.78"
            - "node_rancher_13:172.31.6.82"
            - "node_rancher_14:172.31.15.116"
            - "node_rancher_16:172.31.1.182"
