version: '2'
services:
  checkmk:
    image: checkmk/check-mk-raw:1.6.0-latest
    container_name: check_mk
    restart: always
    volumes:
     - /home/denisrfe/volume/clientes/checkmk:/omd/sites
    ports:
      - "8081:5000"

