apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: checkmk
  name: checkmk
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: checkmk
    spec:
      containers:
      - image: checkmk/check-mk-raw:1.6.0-latest
        name: check-mk
        ports:
        - containerPort: 5000
        resources: {}
        volumeMounts:
        - mountPath: /omd/sites
          name: checkmk-data
      restartPolicy: Always
      volumes:
      - name: checkmk-data
        persistentVolumeClaim:
          claimName: checkmk-data
status: {}
